name: Create Release PR from staging to production
on:
  push:
    branches:
      - staging
jobs:
  gitPrRelease:
    name: git-pr-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: git-pr-release
      uses: bakunyo/git-pr-release-action@master
      with:
        args: '--squashed'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: production
        GIT_PR_RELEASE_BRANCH_STAGING: staging
        GIT_PR_RELEASE_LABELS: release
        GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
        TZ: Asia/Tokyo
